#!/bin/bash

function createCUSTOMER() {
  echo "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/CUSTOMER.fundflow.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/CUSTOMER.fundflow.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:7054 --caname ca-CUSTOMER --tls.certfiles "${PWD}/organizations/fabric-ca/CUSTOMER/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-CUSTOMER.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-CUSTOMER.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-CUSTOMER.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-CUSTOMER.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/CUSTOMER.fundflow.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy CUSTOMER's CA cert to CUSTOMER's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/CUSTOMER.fundflow.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/CUSTOMER/ca-cert.pem" "${PWD}/organizations/peerOrganizations/CUSTOMER.fundflow.com/msp/tlscacerts/ca.crt"

  # Copy CUSTOMER's CA cert to CUSTOMER's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/CUSTOMER.fundflow.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/CUSTOMER/ca-cert.pem" "${PWD}/organizations/peerOrganizations/CUSTOMER.fundflow.com/tlsca/tlsca.CUSTOMER.fundflow.com-cert.pem"

  # Copy CUSTOMER's CA cert to CUSTOMER's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/CUSTOMER.fundflow.com/ca"
  cp "${PWD}/organizations/fabric-ca/CUSTOMER/ca-cert.pem" "${PWD}/organizations/peerOrganizations/CUSTOMER.fundflow.com/ca/ca.CUSTOMER.fundflow.com-cert.pem"

  echo "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-CUSTOMER --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/CUSTOMER/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering user"
  set -x
  fabric-ca-client register --caname ca-CUSTOMER --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/CUSTOMER/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-CUSTOMER --id.name CUSTOMERadmin --id.secret CUSTOMERadminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/CUSTOMER/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:7054 --caname ca-CUSTOMER -M "${PWD}/organizations/peerOrganizations/CUSTOMER.fundflow.com/peers/peer0.CUSTOMER.fundflow.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/CUSTOMER/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/CUSTOMER.fundflow.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/CUSTOMER.fundflow.com/peers/peer0.CUSTOMER.fundflow.com/msp/config.yaml"

  echo "Generating the peer0-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:7054 --caname ca-CUSTOMER -M "${PWD}/organizations/peerOrganizations/CUSTOMER.fundflow.com/peers/peer0.CUSTOMER.fundflow.com/tls" --enrollment.profile tls --csr.hosts peer0.CUSTOMER.fundflow.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/CUSTOMER/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/CUSTOMER.fundflow.com/peers/peer0.CUSTOMER.fundflow.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/CUSTOMER.fundflow.com/peers/peer0.CUSTOMER.fundflow.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/CUSTOMER.fundflow.com/peers/peer0.CUSTOMER.fundflow.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/CUSTOMER.fundflow.com/peers/peer0.CUSTOMER.fundflow.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/CUSTOMER.fundflow.com/peers/peer0.CUSTOMER.fundflow.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/CUSTOMER.fundflow.com/peers/peer0.CUSTOMER.fundflow.com/tls/server.key"

  echo "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:7054 --caname ca-CUSTOMER -M "${PWD}/organizations/peerOrganizations/CUSTOMER.fundflow.com/users/User1@CUSTOMER.fundflow.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/CUSTOMER/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/CUSTOMER.fundflow.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/CUSTOMER.fundflow.com/users/User1@CUSTOMER.fundflow.com/msp/config.yaml"

  echo "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://CUSTOMERadmin:CUSTOMERadminpw@localhost:7054 --caname ca-CUSTOMER -M "${PWD}/organizations/peerOrganizations/CUSTOMER.fundflow.com/users/Admin@CUSTOMER.fundflow.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/CUSTOMER/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/CUSTOMER.fundflow.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/CUSTOMER.fundflow.com/users/Admin@CUSTOMER.fundflow.com/msp/config.yaml"
}

function createMO() {
  echo "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/MO.fundflow.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/MO.fundflow.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:8054 --caname ca-MO --tls.certfiles "${PWD}/organizations/fabric-ca/MO/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-MO.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-MO.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-MO.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-MO.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/MO.fundflow.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy MO's CA cert to MO's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/MO.fundflow.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/MO/ca-cert.pem" "${PWD}/organizations/peerOrganizations/MO.fundflow.com/msp/tlscacerts/ca.crt"

  # Copy MO's CA cert to MO's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/MO.fundflow.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/MO/ca-cert.pem" "${PWD}/organizations/peerOrganizations/MO.fundflow.com/tlsca/tlsca.MO.fundflow.com-cert.pem"

  # Copy MO's CA cert to MO's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/MO.fundflow.com/ca"
  cp "${PWD}/organizations/fabric-ca/MO/ca-cert.pem" "${PWD}/organizations/peerOrganizations/MO.fundflow.com/ca/ca.MO.fundflow.com-cert.pem"

  echo "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-MO --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/MO/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering user"
  set -x
  fabric-ca-client register --caname ca-MO --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/MO/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-MO --id.name MOadmin --id.secret MOadminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/MO/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:8054 --caname ca-MO -M "${PWD}/organizations/peerOrganizations/MO.fundflow.com/peers/peer0.MO.fundflow.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/MO/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/MO.fundflow.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/MO.fundflow.com/peers/peer0.MO.fundflow.com/msp/config.yaml"

  echo "Generating the peer0-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:8054 --caname ca-MO -M "${PWD}/organizations/peerOrganizations/MO.fundflow.com/peers/peer0.MO.fundflow.com/tls" --enrollment.profile tls --csr.hosts peer0.MO.fundflow.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/MO/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/MO.fundflow.com/peers/peer0.MO.fundflow.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/MO.fundflow.com/peers/peer0.MO.fundflow.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/MO.fundflow.com/peers/peer0.MO.fundflow.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/MO.fundflow.com/peers/peer0.MO.fundflow.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/MO.fundflow.com/peers/peer0.MO.fundflow.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/MO.fundflow.com/peers/peer0.MO.fundflow.com/tls/server.key"

  echo "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:8054 --caname ca-MO -M "${PWD}/organizations/peerOrganizations/MO.fundflow.com/users/User1@MO.fundflow.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/MO/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/MO.fundflow.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/MO.fundflow.com/users/User1@MO.fundflow.com/msp/config.yaml"

  echo "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://MOadmin:MOadminpw@localhost:8054 --caname ca-MO -M "${PWD}/organizations/peerOrganizations/MO.fundflow.com/users/Admin@MO.fundflow.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/MO/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/MO.fundflow.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/MO.fundflow.com/users/Admin@MO.fundflow.com/msp/config.yaml"
}


function createDMO() {
  echo "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/DMO.fundflow.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/DMO.fundflow.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:11054 --caname ca-DMO --tls.certfiles "${PWD}/organizations/fabric-ca/DMO/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-11054-ca-DMO.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-11054-ca-DMO.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-11054-ca-DMO.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-11054-ca-DMO.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/DMO.fundflow.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy DMO's CA cert to DMO's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/DMO.fundflow.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/DMO/ca-cert.pem" "${PWD}/organizations/peerOrganizations/DMO.fundflow.com/msp/tlscacerts/ca.crt"

  # Copy DMO's CA cert to DMO's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/DMO.fundflow.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/DMO/ca-cert.pem" "${PWD}/organizations/peerOrganizations/DMO.fundflow.com/tlsca/tlsca.DMO.fundflow.com-cert.pem"

  # Copy DMO's CA cert to DMO's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/DMO.fundflow.com/ca"
  cp "${PWD}/organizations/fabric-ca/DMO/ca-cert.pem" "${PWD}/organizations/peerOrganizations/DMO.fundflow.com/ca/ca.DMO.fundflow.com-cert.pem"

  echo "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-DMO --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/DMO/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering user"
  set -x
  fabric-ca-client register --caname ca-DMO --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/DMO/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-DMO --id.name DMOadmin --id.secret DMOadminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/DMO/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:11054 --caname ca-DMO -M "${PWD}/organizations/peerOrganizations/DMO.fundflow.com/peers/peer0.DMO.fundflow.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/DMO/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/DMO.fundflow.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/DMO.fundflow.com/peers/peer0.DMO.fundflow.com/msp/config.yaml"

  echo "Generating the peer0-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:11054 --caname ca-DMO -M "${PWD}/organizations/peerOrganizations/DMO.fundflow.com/peers/peer0.DMO.fundflow.com/tls" --enrollment.profile tls --csr.hosts peer0.DMO.fundflow.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/DMO/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/DMO.fundflow.com/peers/peer0.DMO.fundflow.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/DMO.fundflow.com/peers/peer0.DMO.fundflow.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/DMO.fundflow.com/peers/peer0.DMO.fundflow.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/DMO.fundflow.com/peers/peer0.DMO.fundflow.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/DMO.fundflow.com/peers/peer0.DMO.fundflow.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/DMO.fundflow.com/peers/peer0.DMO.fundflow.com/tls/server.key"

  echo "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:11054 --caname ca-DMO -M "${PWD}/organizations/peerOrganizations/DMO.fundflow.com/users/User1@DMO.fundflow.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/DMO/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/DMO.fundflow.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/DMO.fundflow.com/users/User1@DMO.fundflow.com/msp/config.yaml"

  echo "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://DMOadmin:DMOadminpw@localhost:11054 --caname ca-DMO -M "${PWD}/organizations/peerOrganizations/DMO.fundflow.com/users/Admin@DMO.fundflow.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/DMO/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/DMO.fundflow.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/DMO.fundflow.com/users/Admin@DMO.fundflow.com/msp/config.yaml"
}

function createDHS() {
  echo "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/DHS.fundflow.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/DHS.fundflow.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:10054 --caname ca-DHS --tls.certfiles "${PWD}/organizations/fabric-ca/DHS/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-10054-ca-DHS.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-10054-ca-DHS.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-10054-ca-DHS.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-10054-ca-DHS.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/DHS.fundflow.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy DHS's CA cert to DHS's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/DHS.fundflow.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/DHS/ca-cert.pem" "${PWD}/organizations/peerOrganizations/DHS.fundflow.com/msp/tlscacerts/ca.crt"

  # Copy DHS's CA cert to DHS's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/DHS.fundflow.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/DHS/ca-cert.pem" "${PWD}/organizations/peerOrganizations/DHS.fundflow.com/tlsca/tlsca.DHS.fundflow.com-cert.pem"

  # Copy DHS's CA cert to DHS's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/DHS.fundflow.com/ca"
  cp "${PWD}/organizations/fabric-ca/DHS/ca-cert.pem" "${PWD}/organizations/peerOrganizations/DHS.fundflow.com/ca/ca.DHS.fundflow.com-cert.pem"

  echo "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-DHS --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/DHS/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering user"
  set -x
  fabric-ca-client register --caname ca-DHS --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/DHS/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-DHS --id.name DHSadmin --id.secret DHSadminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/DHS/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:10054 --caname ca-DHS -M "${PWD}/organizations/peerOrganizations/DHS.fundflow.com/peers/peer0.DHS.fundflow.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/DHS/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/DHS.fundflow.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/DHS.fundflow.com/peers/peer0.DHS.fundflow.com/msp/config.yaml"

  echo "Generating the peer0-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:10054 --caname ca-DHS -M "${PWD}/organizations/peerOrganizations/DHS.fundflow.com/peers/peer0.DHS.fundflow.com/tls" --enrollment.profile tls --csr.hosts peer0.DHS.fundflow.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/DHS/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/DHS.fundflow.com/peers/peer0.DHS.fundflow.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/DHS.fundflow.com/peers/peer0.DHS.fundflow.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/DHS.fundflow.com/peers/peer0.DHS.fundflow.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/DHS.fundflow.com/peers/peer0.DHS.fundflow.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/DHS.fundflow.com/peers/peer0.DHS.fundflow.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/DHS.fundflow.com/peers/peer0.DHS.fundflow.com/tls/server.key"

  echo "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:10054 --caname ca-DHS -M "${PWD}/organizations/peerOrganizations/DHS.fundflow.com/users/User1@DHS.fundflow.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/DHS/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/DHS.fundflow.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/DHS.fundflow.com/users/User1@DHS.fundflow.com/msp/config.yaml"

  echo "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://DHSadmin:DHSadminpw@localhost:10054 --caname ca-DHS -M "${PWD}/organizations/peerOrganizations/DHS.fundflow.com/users/Admin@DHS.fundflow.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/DHS/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/DHS.fundflow.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/DHS.fundflow.com/users/Admin@DHS.fundflow.com/msp/config.yaml"
}

function createOrderer() {
  echo "Enrolling the CA admin"
  mkdir -p organizations/ordererOrganizations/fundflow.com

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/ordererOrganizations/fundflow.com

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:9054 --caname ca-orderer --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/ordererOrganizations/fundflow.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy orderer org's CA cert to orderer org's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/ordererOrganizations/fundflow.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem" "${PWD}/organizations/ordererOrganizations/fundflow.com/msp/tlscacerts/tlsca.fundflow.com-cert.pem"

  # Copy orderer org's CA cert to orderer org's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/ordererOrganizations/fundflow.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem" "${PWD}/organizations/ordererOrganizations/fundflow.com/tlsca/tlsca.fundflow.com-cert.pem"

  echo "Registering orderer"
  set -x
  fabric-ca-client register --caname ca-orderer --id.name orderer --id.secret ordererpw --id.type orderer --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering the orderer admin"
  set -x
  fabric-ca-client register --caname ca-orderer --id.name ordererAdmin --id.secret ordererAdminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Generating the orderer msp"
  set -x
  fabric-ca-client enroll -u https://orderer:ordererpw@localhost:9054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/fundflow.com/orderers/orderer.fundflow.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/ordererOrganizations/fundflow.com/msp/config.yaml" "${PWD}/organizations/ordererOrganizations/fundflow.com/orderers/orderer.fundflow.com/msp/config.yaml"

  echo "Generating the orderer-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://orderer:ordererpw@localhost:9054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/fundflow.com/orderers/orderer.fundflow.com/tls" --enrollment.profile tls --csr.hosts orderer.fundflow.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the orderer's tls directory that are referenced by orderer startup config
  cp "${PWD}/organizations/ordererOrganizations/fundflow.com/orderers/orderer.fundflow.com/tls/tlscacerts/"* "${PWD}/organizations/ordererOrganizations/fundflow.com/orderers/orderer.fundflow.com/tls/ca.crt"
  cp "${PWD}/organizations/ordererOrganizations/fundflow.com/orderers/orderer.fundflow.com/tls/signcerts/"* "${PWD}/organizations/ordererOrganizations/fundflow.com/orderers/orderer.fundflow.com/tls/server.crt"
  cp "${PWD}/organizations/ordererOrganizations/fundflow.com/orderers/orderer.fundflow.com/tls/keystore/"* "${PWD}/organizations/ordererOrganizations/fundflow.com/orderers/orderer.fundflow.com/tls/server.key"

  # Copy orderer org's CA cert to orderer's /msp/tlscacerts directory (for use in the orderer MSP definition)
  mkdir -p "${PWD}/organizations/ordererOrganizations/fundflow.com/orderers/orderer.fundflow.com/msp/tlscacerts"
  cp "${PWD}/organizations/ordererOrganizations/fundflow.com/orderers/orderer.fundflow.com/tls/tlscacerts/"* "${PWD}/organizations/ordererOrganizations/fundflow.com/orderers/orderer.fundflow.com/msp/tlscacerts/tlsca.fundflow.com-cert.pem"

  echo "Generating the admin msp"
  set -x
  fabric-ca-client enroll -u https://ordererAdmin:ordererAdminpw@localhost:9054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/fundflow.com/users/Admin@fundflow.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/ordererOrganizations/fundflow.com/msp/config.yaml" "${PWD}/organizations/ordererOrganizations/fundflow.com/users/Admin@fundflow.com/msp/config.yaml"
}

createCUSTOMER
createMO
createDMO
createDHS
createOrderer
